version: "2.2"
services:
  sql-server-db:
    container_name: sql-server-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: "Earth1234!"